version: '3.8'

services:
  postgis:  
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"         # Map container port 5000 to host port 5000
    env_file:
      - .env                # Load environment variables
    command: flask run --host=0.0.0.0 --port=5000  # Override to run Flask correctly
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    restart: always         # Restart policy for production

  worker:
    build: .
    env_file:
      - .env
    command: ["python", "worker.py"]  # Run the worker script
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"         # Expose Redis on port 6379
    restart: always


volumes:
  postgres-data: